### ISSUE TITLE
[IAR] : connection fails on Nucleo_F429ZI.

### ISSUE THREAD

**Issue by ashok-rao** [ARMmbed/oob-mbed-os-example-mesh-minimal#3]
RC2, Steps to reproduce:
$> mbed import https://github.com/ARMmbed/oob-mbed-os-example-mesh-minimal
$> cd oob-mbed-os-example-mesh-minimal
$> cd mbed-os
$> mbed update mbed-os-5.2.0-rc2
$> cd..
$> mbed compile -t IAR -m NUCLEO_F429ZI

Application build success. Build log attached here:

[RC2_mesh_minimal_F429ZI_IAR_Build_success.txt](https://github.com/ARMmbed/oob-mbed-os-example-mesh-minimal/files/525114/RC2_mesh_minimal_F429ZI_IAR_Build_success.txt)

Update the firmware for the border router with:
https://github.com/ARMmbed/mbed-os-example-client/blob/master/GW_Binary/gateway6LoWPANStatic.bin 

Connect border router to ethernet switch via ethernet cable. Power up the router, flash new firmware, wait for it to acquire IP address.

Copy application binary to target platform and reset. The application does not wait in the "connecting" state. As soon as the target is reset, it prints "connecting..connection failure" (instantly). Hope this helps.

Screenshots below: (COM12 = target - nucleoF429zi + at233 and COM14 = router)

![iar_connection_failure](https://cloud.githubusercontent.com/assets/17567812/19319144/797e2eea-90a3-11e6-954e-76141b8fd18d.jpg)

The mbed_app.json file I'm using:
![mbed_app json](https://cloud.githubusercontent.com/assets/17567812/19319244/f0615208-90a3-11e6-832d-4f676a304b18.jpg)

**Comment by c1728p9** [comment]
Hi @	ashok-rao, are you using the atmel RF shield with a PCB antennna or with a chip antenna?

**Comment by ashok-rao** [comment]
@c1728p9 , I'm using the one with chip antenna. Both the router and the shield are literally sitting next to each other as well.

**Comment by SeppoTakalo** [comment]
Has this been tested with GCC_ARM and ARM compilers? Does the issue remain with those?

**Comment by ashok-rao** [comment]
@SeppoTakalo , the tests PASS with ARMCC and GCC_ARM and it works smoothly..the issue occurs only with IAR.

**Comment by c1728p9** [comment]
The root cause is here:
https://github.com/ARMmbed/mbed-os/issues/2956

**Comment by ashok-rao** [comment]
RC3, Issue still persists. Same as reported above.

**Comment by SeppoTakalo** [comment]
The linked root cause is still open. So it was not fixed in RC3.

**Comment by c1728p9** [comment]
@ashok-rao can you check the sha of mbed-os that you used for this in RC3?

**Comment by SeppoTakalo** [comment]
Or preferably start with clean `mbed import <URL>`

**Comment by ashok-rao** [comment]
@c1728p9 @SeppoTakalo , I started with a fresh import and it works!! Also, the commit # I was using earlier was #87368ce791c . I think we can close this issue now.

**Comment by SeppoTakalo** [comment]
Re-tested with GCC. Works fine.
Need to find IAR tomorrow.

```
$ mbed ls
mbed-os-example-mesh-minimal (57574347e016)
|- atmel-rf-driver (c1b7ba3c2e9a)
|- mbed-os (873686ce791c)
`- mcr20a-rf-driver (d8810e105d7d)
```

From device:
```
Connecting...
connected. IP = 2001:999:22:9ca2:fec2:3d00:5:2de5
```

**Comment by ashok-rao** [comment]
Connecting...
connected. IP = fd00:ff1:ce0b:a5e0:fec2:3d00:4:726a


Link: oob-mbed-os-example-mesh-minimal
Elf2Bin: oob-mbed-os-example-mesh-minimal
+-----------------------------+--------+-------+-------+
| Module                      |  .text | .data |  .bss |
+-----------------------------+--------+-------+-------+
| Misc                        | 165292 |  1204 |  2322 |
| drivers                     |   2828 |     0 |   196 |
| features/FEATURE_COMMON_PAL |   5852 |    96 |  8381 |
| features/FEATURE_LWIP       |     44 |     0 | 12560 |
| features/frameworks         |     48 |     0 |     0 |
| features/mbedtls            |   5914 |     0 |  8748 |
| features/nanostack          |   5298 |     0 | 10072 |
| hal                         |    780 |     0 |     8 |
| platform                    |   1734 |     0 |   108 |
| rtos                        |    626 |     4 |     4 |
| rtos/rtx                    |   7066 |    36 |  7128 |
| targets/TARGET_STM          |  11984 |    72 |  1340 |
| Subtotals                   | 207466 |  1412 | 50867 |
+-----------------------------+--------+-------+-------+
Allocated Heap: 49152 bytes
Allocated Stack: 24576 bytes
Total Static RAM memory (data + bss): 52279 bytes
Total RAM memory (data + bss + heap + stack): 126007 bytes
Total Flash memory (text + data + misc): 208878 bytes
Object file test_env.o is not unique! It could be made from: ..\mbed-os\features\frameworks\greentea-client\source\test_en
Image: ..\BUILD\nucleo_f429zi\IAR\oob-mbed-os-example-mesh-minimal.bin

C:\temp\mesh_minimal\nucleo_f429zi\oob-mbed-os-example-mesh-minimal\mbed-os>ping fd00:ff1:ce0b:a5e0:fec2:3d00:4:726a

Pinging fd00:ff1:ce0b:a5e0:fec2:3d00:4:726a with 32 bytes of data:
Reply from fd00:ff1:ce0b:a5e0:fec2:3d00:4:726a: time=19ms
Reply from fd00:ff1:ce0b:a5e0:fec2:3d00:4:726a: time=19ms
Reply from fd00:ff1:ce0b:a5e0:fec2:3d00:4:726a: time=16ms
Reply from fd00:ff1:ce0b:a5e0:fec2:3d00:4:726a: time=15ms

Ping statistics for fd00:ff1:ce0b:a5e0:fec2:3d00:4:726a:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 15ms, Maximum = 19ms, Average = 17ms

C:\temp\mesh_minimal\nucleo_f429zi\oob-mbed-os-example-mesh-minimal\mbed-os>mbed ls
mbed-os (873686ce791c)

**Comment by SeppoTakalo** [comment]
Thank you for verifying this.
