### ISSUE TITLE
[Online IDE] : Compilation fails.

### ISSUE THREAD

**Issue by ashok-rao** [ARMmbed/oob-mbed-os-example-mesh-minimal#4]
Import the example from URL using import wizard. Make changes to mbed_app.json, click "compile". The online IDE fails with the following message:
![mesh_minimal_online_ide](https://cloud.githubusercontent.com/assets/17567812/19345724/a1c4eea4-9137-11e6-985f-8cdc010a98ab.jpg)

**Comment by SeppoTakalo** [comment]
CC: @MarceloSalazar @sg- Who can debug these online IDE errors?

**Comment by MarceloSalazar** [comment]
@screamerbg please have a look

**Comment by sg-** [comment]
@screamerbg

**Comment by MarceloSalazar** [comment]
Online IDE fixed and should be retested for RC3
The IDE has to be used in beta mode - instructions will be provided

**Comment by ashok-rao** [comment]
RC3, using developer version of online IDE still results in same error. Screenshot below:

![mesh_minimal_online_ide](https://cloud.githubusercontent.com/assets/17567812/19436206/b2ed3e34-9466-11e6-8b2f-047b6daa2eb1.jpg)

**Comment by MarceloSalazar** [comment]
@screamerbg please help asap

**Comment by ashok-rao** [comment]
Issue fixed in RC3. Closing. Thank you.
