### ISSUE TITLE
[Online IDE] : Fails with K64F.

### ISSUE THREAD

**Issue by ashok-rao** [ARMmbed/oob-mbed-os-example-mesh-minimal#5]
Steps to reproduce:
1. Import into Online IDE using import wizard from URL as a program and tick the "update to latest versions" tickbox.
2. Once imported successfully, make changes to mbed_app.json file as required.
3. Compile.

Fails with the following:
![online_ide_k64f_fail](https://cloud.githubusercontent.com/assets/17567812/19391379/3df6b356-9224-11e6-8bed-5031ebfe4a3a.jpg)

**Comment by MarceloSalazar** [comment]
This is expected to work when using the developer version of the IDE.
Instructions will be sent soon.

**Comment by ashok-rao** [comment]
RC3, using developer version of online IDE, issue still persists. Please see screenshot below.

![mesh_minimal_online_ide_k64f](https://cloud.githubusercontent.com/assets/17567812/19436791/11e073b8-946a-11e6-8dbc-a880c9b3253b.jpg)

**Comment by MarceloSalazar** [comment]
This should be fixed now. Please re-test.

**Comment by ashok-rao** [comment]
Issue fixed. Closing. Thank you.
