### ISSUE TITLE
(doc) wrong instructions to update border router firmware

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/oob-mbed-os-example-mesh-minimal#6]
The documentation on this section is wrong:
https://github.com/ARMmbed/oob-mbed-os-example-mesh-minimal#update-the-firmware-of-the-border-router

It should explain:

- If using the K64 as Border Router, you have to use [K64-Border-Router](https://github.com/ARMmbed/k64f-border-router) application configured with static backhaul configuration

- If using the [mbed gateway](mbed 6LoWPAN gateway router), then use the static firmware from the [mbed Client example](https://github.com/ARMmbed/mbed-os-example-client/blob/master/GW_Binary/gateway6LoWPANStatic.bin)

@SeppoTakalo

**Comment by SeppoTakalo** [comment]
This application have no requirements of using static ones. Static ones are good for testing but dynamic ones work also if your network infrastructure is supplying IPv6 address.

For testing purposes, it might be useful to have separate documentation of testing with non-routable static network but I don't feel confident of leaving that information on the example applications `README.md`
Or maybe it is the right place.

**Comment by MarceloSalazar** [comment]
Thanks for clarifying this.

I believe it's worth commenting that both static and dynamic modes are expected to work (I didn't know this). The person testing the example will have to decide which one they prefer.

Btw, I still believe we need to comment that there are two border routers supported: k64 and mbed gatewatey (regardless on whether you use static or dynamic backhaul mode). The current document is mixing this info.

**Comment by MarceloSalazar** [comment]
Find proposal here: https://github.com/ARMmbed/oob-mbed-os-example-mesh-minimal/pull/8

**Comment by MarceloSalazar** [comment]
Doc merged https://github.com/ARMmbed/oob-mbed-os-example-mesh-minimal/pull/8
