### ISSUE TITLE
remove Thread specific settings

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/oob-mbed-os-example-mesh-minimal#9]
This example is 6lowpan only.
I don't see the reason why we are having thread config. See lines:

- https://github.com/ARMmbed/oob-mbed-os-example-mesh-minimal/blob/master/mbed_app.json#L22
- https://github.com/ARMmbed/oob-mbed-os-example-mesh-minimal/blob/master/mbed_app.json#L23
- https://github.com/ARMmbed/oob-mbed-os-example-mesh-minimal/blob/master/mbed_app.json#L24

@SeppoTakalo @hasnainvirk what do you think?

**Comment by hasnainvirk** [comment]
@MarceloSalazar Why do you think that it is 6LOWPAN only ? 
If you use MESH_LOWPAN as your mesh type then any thread settings will not have an effect.

**Comment by MarceloSalazar** [comment]
Right, but happens if we compile with `FEATURE_THREAD_xxxx`
Is this expected to work? or are there other requirements?

**Comment by hasnainvirk** [comment]
Yes. For example:

"target.features_add": ["NANOSTACK", "THREAD_ROUTER", "COMMON_PAL"],
"mbed-mesh-api.6lowpan-nd-device-type": "MESH_DEVICE_TYPE_THREAD_SLEEPY_END_DEVICE",

**Comment by MarceloSalazar** [comment]
Thanks for confirming. Rejecting and closing ;)
